"""
ingest_weather.py — Ingest hourly temperature (observed + day-ahead forecast)
for each config.WEATHER_LOCATIONS point from Open-Meteo.

    python ingest_weather.py --start 2022-01-01 --end 2024-12-31
    python ingest_weather.py --incremental

Two sources, merged per hour:
  - Historical Weather API (ERA5 reanalysis)       -> *_obs_* columns
  - Previous Runs API (GFS, fixed lead times)       -> *_fcst_d1_* / *_fcst_d2_* columns

Variables: temperature, wind speed, relative humidity, cloud cover. The WWP
and THI columns (PJM Manual 19) are generated by Postgres from these — see
db_setup.py. GFS archives the non-temperature forecasts only from 2024-01-20.

Open-Meteo needs no API key and is independent of the PJM key's 6 req/min
limit, so this can run alongside the PJM ingests. One request covers a whole
year, so a full backfill is only a handful of requests.
"""

import argparse
import logging
import time
from datetime import date, datetime, timedelta

import psycopg2
import requests

from config import (DB, DEFAULT_START_DATE, OPEN_METEO_ARCHIVE_URL,
                    OPEN_METEO_PREVIOUS_RUNS_URL, WEATHER_LOCATIONS)

log = logging.getLogger(__name__)
logging.basicConfig(level=logging.INFO, format="%(asctime)s  %(levelname)-8s  %(message)s")

REQUEST_DELAY_SECONDS = 1.0   # be polite to the free tier
MAX_RETRIES           = 5
CHUNK_DAYS            = 366

# Open-Meteo variable -> weather_hourly column, per source.
OBS_COLUMNS = {
    "temperature_2m":       "temp_obs_f",
    "wind_speed_10m":       "wind_obs_mph",
    "relative_humidity_2m": "rh_obs_pct",
    "cloud_cover":          "cloud_obs_pct",
}
FCST_COLUMNS = {}
for lead in (1, 2):
    for var, col in OBS_COLUMNS.items():
        FCST_COLUMNS[f"{var}_previous_day{lead}"] = col.replace("_obs_", f"_fcst_d{lead}_")
DATA_COLUMNS = list(OBS_COLUMNS.values()) + list(FCST_COLUMNS.values())

# GFS interpolation occasionally returns -1% / 101% cloud cover; clamp
# percentages to their physical range.
PCT_COLUMNS = {i for i, c in enumerate(DATA_COLUMNS) if c.endswith("_pct")}


def clamp_pct(row: list) -> list:
    return [min(max(v, 0), 100) if i in PCT_COLUMNS and v is not None else v
            for i, v in enumerate(row)]


def fetch_hourly(url: str, loc: dict, start: date, end: date, hourly: str, **extra) -> dict:
    """Return {time_str: {var: value}} for one location and date range (UTC)."""
    params = {
        "latitude":         loc["lat"],
        "longitude":        loc["lon"],
        "start_date":       start.isoformat(),
        "end_date":         end.isoformat(),
        "hourly":           hourly,
        "timezone":         "GMT",
        "temperature_unit": "fahrenheit",
        "wind_speed_unit":  "mph",
        **extra,
    }
    for attempt in range(1, MAX_RETRIES + 1):
        try:
            resp = requests.get(url, params=params, timeout=120)
            if resp.status_code == 200:
                break
            log.warning(f"  HTTP {resp.status_code} from {url}: {resp.text[:200]}")
        except requests.RequestException as e:
            log.warning(f"  Request error from {url}: {e}")
        if attempt == MAX_RETRIES:
            raise RuntimeError(f"Open-Meteo request failed after {MAX_RETRIES} attempts: {url}")
        time.sleep(2 ** attempt)

    data = resp.json()["hourly"]
    times = data.pop("time")
    return {t: {var: vals[i] for var, vals in data.items()} for i, t in enumerate(times)}


def upsert_weather_rows(conn, loc: dict, obs: dict, fcst: dict) -> int:
    # COALESCE keeps an existing value when the incoming one is null, but a new
    # non-null value always overwrites — recent ERA5 values are provisional.
    cols = ", ".join(DATA_COLUMNS)
    placeholders = ", ".join(["%s"] * (3 + len(DATA_COLUMNS)))
    updates = ",\n            ".join(
        f"{c} = COALESCE(EXCLUDED.{c}, weather_hourly.{c})" for c in DATA_COLUMNS)
    sql = f"""
        INSERT INTO weather_hourly
            (datetime_beginning_utc, location, zone, {cols})
        VALUES ({placeholders})
        ON CONFLICT (datetime_beginning_utc, location) DO UPDATE SET
            zone       = EXCLUDED.zone,
            {updates},
            updated_at = NOW()
    """
    cur = conn.cursor()
    n = 0
    for t in sorted(set(obs) | set(fcst)):
        o, f = obs.get(t, {}), fcst.get(t, {})
        row = clamp_pct([o.get(v) for v in OBS_COLUMNS] + [f.get(v) for v in FCST_COLUMNS])
        if all(v is None for v in row):
            continue
        cur.execute(sql, (t + "+00:00", loc["location"], loc["zone"], *row))
        n += 1
    conn.commit()
    cur.close()
    return n


def sync_locations(conn):
    """Make weather_locations match config.WEATHER_LOCATIONS exactly — the
    weather_zone_hourly view takes its stations and weights from this table."""
    cur = conn.cursor()
    cur.execute("DELETE FROM weather_locations")
    for loc in WEATHER_LOCATIONS:
        cur.execute(
            "INSERT INTO weather_locations (location, zone, lat, lon, weight) VALUES (%s, %s, %s, %s, %s)",
            (loc["location"], loc["zone"], loc["lat"], loc["lon"], loc["weight"]))
    conn.commit()
    cur.close()


def select_locations(codes: list[str] | None) -> list[dict]:
    if not codes:
        return WEATHER_LOCATIONS
    known = {loc["location"]: loc for loc in WEATHER_LOCATIONS}
    unknown = set(codes) - set(known)
    if unknown:
        raise SystemExit(f"Unknown location(s) {sorted(unknown)}; config has {sorted(known)}")
    return [known[c] for c in codes]


def ingest_weather(start_date: str, end_date: str, locations: list[dict] | None = None):
    conn  = psycopg2.connect(**DB)
    sync_locations(conn)
    start = datetime.fromisoformat(start_date).date()
    end   = datetime.fromisoformat(end_date).date()
    total = 0

    for loc in locations or WEATHER_LOCATIONS:
        chunk_start = start
        while chunk_start <= end:
            chunk_end = min(chunk_start + timedelta(days=CHUNK_DAYS - 1), end)
            log.info(f"Fetching weather {loc['location']} ({loc['zone']}) {chunk_start} → {chunk_end}...")

            obs = fetch_hourly(OPEN_METEO_ARCHIVE_URL, loc, chunk_start, chunk_end,
                               ",".join(OBS_COLUMNS))
            time.sleep(REQUEST_DELAY_SECONDS)
            fcst = fetch_hourly(OPEN_METEO_PREVIOUS_RUNS_URL, loc, chunk_start, chunk_end,
                                ",".join(FCST_COLUMNS), models="gfs_seamless")
            time.sleep(REQUEST_DELAY_SECONDS)

            n = upsert_weather_rows(conn, loc, obs, fcst)
            total += n
            log.info(f"  Upserted {n} rows")
            chunk_start = chunk_end + timedelta(days=1)

    conn.close()
    log.info(f"Weather ingest complete. Total rows upserted: {total}")


def incremental_weather(lookback_days: int = 14):
    """Re-fetch the last `lookback_days` through today and upsert.

    Range fetches are cheap and the upsert is idempotent, so there's no
    pjm_ingest_log bookkeeping — the lookback just needs to exceed the ERA5
    revision window (~5 days) plus the weekly cron gap.

    A location with no rows yet (e.g. just added to config) is backfilled from
    DEFAULT_START_DATE first — weather_zone_hourly needs every location in a
    zone to have data, so a short-history station would blank out the zone.
    """
    conn = psycopg2.connect(**DB)
    cur = conn.cursor()
    cur.execute("SELECT DISTINCT location FROM weather_hourly")
    have = {r[0] for r in cur.fetchall()}
    cur.close()
    conn.close()

    end = date.today()
    new = [loc for loc in WEATHER_LOCATIONS if loc["location"] not in have]
    if new:
        log.info(f"No existing data for {[l['location'] for l in new]} — backfilling from {DEFAULT_START_DATE}")
        ingest_weather(DEFAULT_START_DATE, end.isoformat(), new)

    ingest_weather((end - timedelta(days=lookback_days)).isoformat(), end.isoformat())


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--start",       default=DEFAULT_START_DATE)
    parser.add_argument("--end",         default=date.today().isoformat())
    parser.add_argument("--incremental", action="store_true")
    parser.add_argument("--locations",   help="comma-separated location codes (default: all in config)")
    args = parser.parse_args()

    if args.incremental:
        incremental_weather()
    else:
        locs = select_locations(args.locations.split(",") if args.locations else None)
        ingest_weather(args.start, args.end, locs)
